### ISSUE TITLE
make FileSystemEvents framework available via cocoapods

### ISSUE THREAD

**Issue by lenada** [Eonil/FileSystemEvents#1]
@Eonil thank you for `EonilFileSystemEvents` :+1: 
To make it easier for other people to include and use this framwork in their projects It would be great to add it to cocoapods. I played around with a local podspec for `EonilFileSystemEvents` trying to link against my project. As I am a total Xcode/swift noob I did not get very far.
If you generally like the idea of cocoapods, and have not objections against adding a podspec I would be happy to send a pull-request with what I currently have.

**Comment by Eonil** [comment]
Hello @lenada , thanks for your interest and care.
Actually I haven't used CocoaPods, and personally don't feel need for it.
Anyway, I know many people are using it, and I think adding support for it will be helpful to many people.
If you have written working support files, I like to add them and see what happens :)

**Comment by Eonil** [comment]
I have played a little with CocoaPods, and I couldn't find a reliable way to support this situation. 

- A dynamic module framework target shared and linked by multiple another dynamic module framework targets defined in multiple projects contained in a workspace.

I close this issue because I don't think CocoaPods properly ready for Swift or dynamic modules currently. Maybe I can re-open this issue later.
