### ISSUE TITLE
how to know if the file is modified only 

### ISSUE THREAD

**Issue by remella** [eonil/FileSystemEvents#10]
if i print event i am getting all the changes but i want to have call back only if the file is modified(ItemModified)

path: xxxxxxxxxxxxxx, flag: ItemRemoved, ItemRenamed, ItemModified, ItemChangeOwner, ID: 33344323), (path: xxxxxxxxxxx, flag: ItemRenamed, ItemFinderInfoMod, ItemXattrMod, ID: 33344417)

**Comment by eonil** [comment]
Hello, @remella. Sorry for late reply.

You can filter specific event like this.

    for ev in events {
        if ev.flag.contains(.itemModified) {
            // Do what you want for modified here...
        }
    }

I updated example [target code](https://github.com/eonil/FileSystemEvents/blob/e437b1d0f74bef20daa1ce07ab33cafb6cd9b316/Project/TestdriveApp/AppDelegate.swift#L36).

If you're looking for a way to *prevent* monitoring of specific event instead of post-filtering, This framework does not support it because I couldn't find a way to do it in Apple's FSEvent level.
